#!/usr/bin/env python
from subprocess import Popen, PIPE

sudo_password = 'admin'
command = 'leapd'.split()

p = Popen(['sudo', '-S'] + command, stdin=PIPE, stderr=PIPE,universal_newlines=True)
sudo_prompt = p.communicate(sudo_password + '\n')[1]
